CREATE TABLE tb_user (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_email VARCHAR(255),
    user_name VARCHAR(255),
    user_password VARCHAR(255),
    PRIMARY KEY (user_id)
);

CREATE TABLE tb_label (
    label_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    label_name VARCHAR(255),
    fk_user_id INTEGER,
    PRIMARY KEY (label_id),
    CONSTRAINT fk_label_user FOREIGN KEY (fk_user_id) REFERENCES tb_user(user_id)
);

CREATE TABLE tb_note (
    note_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    creation_date DATE,
    note_content VARCHAR(255),
    note_title VARCHAR(255),
    user_user_id INTEGER,
    PRIMARY KEY (note_id),
    CONSTRAINT fk_note_user FOREIGN KEY (user_user_id) REFERENCES tb_user(user_id)
);

CREATE TABLE tb_reminder (
    reminder_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    reminder_content VARCHAR(255),
    reminder_date DATE,
    user_user_id INTEGER,
    PRIMARY KEY (reminder_id),
    CONSTRAINT fk_reminder_user FOREIGN KEY (user_user_id) REFERENCES tb_user(user_id)
);

CREATE TABLE tb_track_list_item (
    list_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    list_date DATE,
    list_items VARCHAR(255) ARRAY,
    list_title VARCHAR(255),
    user_user_id INTEGER,
    PRIMARY KEY (list_id),
    CONSTRAINT fk_tracklist_user FOREIGN KEY (user_user_id) REFERENCES tb_user(user_id)
);
    